<?php
/**
 * Copyright © Scalexpert.
 * This file is part of Scalexpert plugin for Magento 2. See COPYING.md for license details.
 *
 * @author    Scalexpert (https://scalexpert.societegenerale.com/)
 * @copyright Scalexpert
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var $block \Scalexpert\Plugin\Block\Onepage\Failure */
?>

<?php if ($block->isScalexpertFailure()):?>
    <p><?= __('Nous sommes désolés, votre demande de financement n\'a pas été acceptée ou une erreur technique est survenue. Nous vous invitons à réessayer ou à réaliser une nouvelle commande en choisissant un autre mode de paiement.') ?></p>
<?php endif; ?>
