<?php
/**
 * Copyright © Scalexpert.
 * This file is part of Scalexpert plugin for Magento 2. See COPYING.md for license details.
 *
 * @author    Scalexpert (https://scalexpert.societegenerale.com/)
 * @copyright Scalexpert
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var Scalexpert\Plugin\Block\FinancingAndInsurance\Product $block */

$productId = $block->getData('product_id');
$price = '';

if (!is_null($block->getData('price'))) {
    $price = $block->getData('price');
}
$warranty = $block->getProductWarranty($productId, $price);
?>

<?php if($warranty && $warranty['enabled']) { ?>
    <div id="warranty" data-bind="scope:'warranty'">
        <script>
            window.scalexepertWarranty = <?php /* @escapeNotVerified */ echo json_encode($warranty); ?>;
        </script>
        <script type="text/x-magento-init">
            {
                "*": {
                    "Magento_Ui/js/core/app": {
                        "components": {
                            "warranty": {
                                "component": "Scalexpert_Plugin/js/view/catalog/warranty"
                            }
                        }
                    }
                }
            }
        </script>
        <div class="scalexpert-box scalexpert-box-warranty" data-bind="class: 'show'">
            <div class="scalexpert-box-title">
                <span data-bind="text: getTitle()"></span>
                <div id="scalexpert-warranty-btn">
                    <img data-bind="attr: {'src': getPictoInfo(), 'alt': 'Information'}" width="16">
                </div>
                <!-- ko if: getLogo() -->
                    <img data-bind="attr: {'src': getLogo(), 'alt': 'Société Générale'}" class="scalexpert-logo" width="55">
                <!--/ko-->
            </div>
            <div class="scalexpert-box-content">
                <!-- ko foreach: {data: getInsurances(), as: 'insurance'} -->
                    <div class="scalexpert-option">
                        <input type="radio" data-bind="attr: {'id': insurance.id, 'value': insurance.code}" name="insurances">
                        <label data-bind="attr: {'for': insurance.id}">
                            <span data-bind="text: insurance.label"></span>
                        </label>
                    </div>
                <!--/ko-->
                <!-- ko if: getSubTitle() -->
                    <div class="scalexpert-description" data-bind="text: getSubTitle()"></div>
                <!--/ko-->
            </div>
            <div class="scalexpert-box-infos">
                <!-- ko if: getInfoTerms() -->
                    <a data-bind="attr: {'href': getInfoTerms()}" target="_blank"><?= __('Product Information Sheet (IPID)'); ?></a>
                <!--/ko-->
                <!-- ko if: getInfoNotice() -->
                    <a data-bind="attr: {'href': getInfoNotice()}" target="_blank"><?= __('Information Notice (IN)'); ?></a>
                <!--/ko-->
            </div>
        </div>
        <div class="scalexpert-modal-container"
             data-bind="mageInit: {
                'Magento_Ui/js/modal/modal':{
                'type': 'popup',
                'trigger': '#scalexpert-warranty-btn',
                'modalClass': 'scalexpert-modal',
                'responsive': true,
                'innerScroll': true,
                'buttons': []
             }}">

            <div class="scalexpert-modal-title">
                <img src="<?= $this->getViewFileUrl('Scalexpert_Plugin::images/umbrella.svg'); ?>" data-bind="attr: {'alt': getTitle()}">
                <span data-bind="text: getTitle()"></span>
            </div>

            <div class="scalexpert-modal-content">
                <div class="scalexpert_subtitle" data-bind="text: getSubTitle()"></div>
                <div data-bind="html: getAdditionalText()"></div>
                <div data-bind="html: getLegalText()"></div>
            </div>

            <div class="scalexpert-modal-bottom">
                <!-- ko if: getInfoTerms() -->
                    <a data-bind="attr: {'href': getInfoTerms()}" target="_blank"><?= __('Product Information Sheet (IPID)'); ?></a>
                <!--/ko-->
                <!-- ko if: getInfoNotice() -->
                    <a data-bind="attr: {'href': getInfoNotice()}" target="_blank"><?= __('Information Notice (IN)'); ?></a>
                <!--/ko-->
            </div>

        </div>

    </div>
<?php } ?>
