<?php
/**
 * Copyright © Scalexpert.
 * This file is part of Scalexpert plugin for Magento 2. See COPYING.md for license details.
 *
 * @author    Scalexpert (https://scalexpert.societegenerale.com/)
 * @copyright Scalexpert
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var $block \Scalexpert\Plugin\Block\Payment\PaymentResponse */
      /** @var \Magento\Framework\Escaper $escaper */ ?>

<?php
$error = $block->getData('error');
$title = $block->getData('title');
$orderId = $block->getData('scalexpert_order_id');
$incrementId = $block->getData('increment_id');
$informationsApi = $block->getFinancialOrder($incrementId);
$status = __($informationsApi['consolidated_status']);
?>

<div class="page-title-wrapper">
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper"><?= $escaper->escapeHtml(__($title)) ?></span>
    </h1>
    <?php if ($block->getCanViewOrder() && $block->getCanPrintOrder()) :?>
        <a href="<?= $escaper->escapeUrl($block->getPrintUrl()) ?>"
           class="action print"
           target="_blank"
           rel="noopener">
            <?= $escaper->escapeHtml(__('Print receipt')) ?>
        </a>
    <?php endif;?>
</div>
<div class="checkout-success">
    <?php if ($incrementId): ?>
        <?php if ($block->getCanViewOrder()): ?>
            <p><?= $escaper->escapeHtml(__('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $escaper->escapeUrl($block->getViewOrderUrl()), $incrementId)), ['a', 'strong']) ?></p>
        <?php  else :?>
            <p><?= $escaper->escapeHtml(__('Your order # is: <span>%1</span>.', $incrementId), ['span']) ?></p>
        <?php endif; ?>

        <p><?= $escaper->escapeHtml(__('The status of your financing request is: <b>%1</b>.', $status), ['b']) ?></p>

        <p><?= $escaper->escapeHtml(__('We\'ll email you an order confirmation with details and tracking info.')) ?></p>
    <?php endif; ?>

    <?php if (!is_null($block->isOrderIsGuest())): ?>
        <?php if ($informationsApi['consolidated_status'] === 'ABORTED'
            || $informationsApi['consolidated_status'] === 'REJECTED'
        ): ?>
            <?php $reorderUrl = $block->getUrl("sales/order/reorder", ['order_id' => $orderId]); ?>
            <p><a href="#" data-post='<?= /* @noEscape */
                $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                    ->getPostData($reorderUrl)
                ?>' class="action primary order">
                    <span><?= $escaper->escapeHtml(__('Reorder')) ?></span>
                </a></p>
        <?php endif; ?>
    <?php endif; ?>


    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= $escaper->escapeUrl($block->getContinueUrl()) ?>"><span><?= $escaper->escapeHtml(__('Continue Shopping')) ?></span></a>
        </div>
    </div>
</div>
