<?php
/** @var Scalexpert\Plugin\Block\Payment\Info $block */
/* @var \Magento\Framework\Escaper $escaper */
$info = $block->getPaymentDetail();
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
?>
<?php if(is_array($info) && !empty($info)):
    $registration = new \DateTime($info['registration_timestamp'], new \DateTimezone('UTC'));
    $update = new \DateTime($info['last_update_timestamp'], new \DateTimezone('UTC')); ?>
    <div><span><?= $escaper->escapeHtml($info['method_title']); ?></span></div><br/>
    <div>
        <span><b><?= $escaper->escapeHtml(__('Buyer financed amount')); ?></b></span> : <span><?= $escaper->escapeHtml($priceHelper->currency($info['buyer_financedAmount'], true, false)); ?></span><br/>
        <span><b><?= $escaper->escapeHtml(__('Consolidated status')); ?></b></span> : <span><?= $escaper->escapeHtml(__($info['consolidated_status'])); ?></span><br/><br/>
        <span><b><?= $escaper->escapeHtml(__('Credit subscription id')); ?></b></span> : <span><?= $escaper->escapeHtml($info['credit_subscription_id']); ?></span><br/>
        <span><b><?= $escaper->escapeHtml(__('Registration timestamp')); ?></b></span> : <span><?= $escaper->escapeHtml($registration->format("Y-m-d H:i:s")); ?></span><br/>
        <span><b><?= $escaper->escapeHtml(__('Last update timestamp')); ?></b></span> : <span><?= $escaper->escapeHtml($update->format("Y-m-d H:i:s")); ?></span><br/>
    </div>
<?php endif; ?>
